variables:
  RUNNER: dev
  ENV: dev
  K8S_CLUSTER: ci-todo/app:minikube
  K8S_NAMESPACE: dev
  DOMAIN: ${ENV}-${CI_COMMIT_REF_SLUG:0:55}.development.com


dev:build:backend:
  variables:
    APP: frontend
  extends: 
    - .dev-rules
    - .build

dev:build:frontend:
  variables:
    APP: backend
  extends: 
    - .dev-rules
    - .build

dev:deploy:
  extends: 
    - .dev-rules
    - .deploy
  environment:
    name: ${ENV}/${CI_COMMIT_REF_SLUG}
    url: https://${ENV}-${CI_COMMIT_REF_SLUG:0:55}.${DOMAIN}
    on_stop: dev:destroy
    deployment_tier: development
    auto_stop_in: 5 minutes
  resource_group: ${ENV}/${CI_COMMIT_REF_SLUG}
  needs:
    - dev:build:backend
    - dev:build:frontend

dev:destroy:
  extends: 
    - .dev-destroy-rules
    - .destroy
  environment:
    name: ${ENV}/${CI_COMMIT_REF_SLUG}
    action: stop
  needs:
    - dev:deploy

