variables:
  RUNNER: dev
  ENV: dev
  K8S_CLUSTER: ci-todo/app:minikube
  K8S_NAMESPACE: dev


dev:build:backend:
  variables:
    APP: frontend
  extends: 
    - .dev-rules
    - .build

dev:build:frontend:
  variables:
    APP: backend
  extends: 
    - .dev-rules
    - .build

dev:deploy:
  extends: 
    - .dev-rules
    - .deploy
  environment:
    on_stop: dev:destroy
    deployment_tier: development
    auto_stop_in: 2 minutes

  needs:
    - dev:build:backend
    - dev:build:frontend

dev:destroy:
  extends: 
    - .dev-rules
    - .destroy
  needs:
    - dev:deploy
  when: manual