variables:
  RUNNER: dev
  ENV: dev

stages:
  - build
  - deploy
  - destroy

.build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - cd ${APP}
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - IMAGE_TAG=${ENV}-${CI_COMMIT_REF_SLUG}
    - IMAGE=${CI_REGISTRY_IMAGE}/${APP}:${IMAGE_TAG}
    - docker build --tag ${IMAGE} .
    - docker push ${IMAGE}
  tags:
    - ${RUNNER}

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  before_script: 
    - kubectl config get-contexts
    - kubectl config use-context ci-todo/app:minikube
  script:
    - kubectl apply -f k8s/
  dependencies:
    - "Build Backend"
    - "Build Frontend"
  tags:
    - ${RUNNER}

destroy:
  stage: destroy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  before_script: 
    - kubectl config get-contexts
    - kubectl config use-context dakual/ci-todo/app:minikube
  script:
    - kubectl delete -f k8s/
  when: manual
  dependencies:
    - deploy
  tags:
    - ${RUNNER}


"Build Backend":
  extends: 
    - .build
  variables:
    APP: frontend

"Build Frontend":
  extends: 
    - .build
  variables:
    APP: backend