{{- range $key, $value := .Values.deployments }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $key }}
  {{- with $value.labels }}
  annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $value.ingress.className }}
  rules:
  - host: {{ $value.ingress.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $key }}
              port:
                number: {{ $value.ingress.port }}
{{- end }}