variables:
  RUNNER: dev
  ENV: dev
  ENV_LONG: development
  AGENT: ci-todo/app:minikube
  DOMAIN: ${ENV}-${CI_COMMIT_REF_SLUG}.example.com
  NAMESPACE: ${ENV}-${CI_COMMIT_REF_SLUG:0:59}
  MYSQL_HOST: "192.168.1.100"
  MYSQL_PORT: 3306
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  MYSQL_DATABASE: ${ENV}-${CI_COMMIT_REF_SLUG:0:59}


dev:build:backend:
  variables:
    APP: frontend
    BUILD_ARGS: '--build-arg REACT_APP_BACKEND_URL=http://api.${DOMAIN}/api'
  extends: 
    - .dev-rules
    - .build

dev:build:frontend:
  variables:
    APP: backend
  extends: 
    - .dev-rules
    - .build

dev:deploy:
  extends: 
    - .dev-rules
    - .deploy
  environment:
    name: ${ENV_LONG}/${CI_COMMIT_REF_SLUG}
    url: https://${DOMAIN}
    on_stop: dev:destroy
    deployment_tier: development
    auto_stop_in: 5 minutes
  resource_group: ${ENV_LONG}/${CI_COMMIT_REF_SLUG}
  needs:
    - dev:build:backend
    - dev:build:frontend

dev:initialize:
  extends:
    - .init-db
  needs:
    - dev:deploy

dev:destroy:
  extends: 
    - .dev-destroy-rules
    - .destroy
  environment:
    name: ${ENV_LONG}/${CI_COMMIT_REF_SLUG}
    action: stop
  needs:
    - dev:deploy

