{{- range $key, $value := .Values.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $value }}
{{- end }}